-- Intel ingest durable event stream with strict RLS and retention tooling.

BEGIN;

CREATE TABLE IF NOT EXISTS public.intel_event_stream (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id text,
  event_name text NOT NULL,
  occurred_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  session_id text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  nonce text,
  signature text
);

ALTER TABLE public.intel_event_stream
  ADD COLUMN IF NOT EXISTS source text GENERATED ALWAYS AS (coalesce(context ->> 'source', 'unknown')) STORED;

ALTER TABLE public.intel_event_stream
  ADD COLUMN IF NOT EXISTS power_mode text GENERATED ALWAYS AS (
    coalesce(context ->> 'powerMode', payload ->> 'powerMode', 'unknown')
  ) STORED;

ALTER TABLE public.intel_event_stream
  ADD COLUMN IF NOT EXISTS threat_level text GENERATED ALWAYS AS (
    coalesce(context ->> 'threatLevel', payload ->> 'dangerLevel', 'unknown')
  ) STORED;

ALTER TABLE public.intel_event_stream
  ALTER COLUMN payload SET DEFAULT '{}'::jsonb,
  ALTER COLUMN context SET DEFAULT '{}'::jsonb,
  ALTER COLUMN ingested_at SET DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'intel_event_stream_event_name_check'
      AND conrelid = 'public.intel_event_stream'::regclass
  ) THEN
    ALTER TABLE public.intel_event_stream
      ADD CONSTRAINT intel_event_stream_event_name_check
      CHECK (event_name = ANY (ARRAY[
        'price.quote_seen',
        'price.anomaly_detected',
        'price.crowd_submitted',
        'negotiation.round_recorded',
        'hazard.zone_state_changed',
        'sos.armed',
        'sos.triggered',
        'sos.deactivated',
        'context.update'
      ]));
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'intel_event_stream_payload_object_check'
      AND conrelid = 'public.intel_event_stream'::regclass
  ) THEN
    ALTER TABLE public.intel_event_stream
      ADD CONSTRAINT intel_event_stream_payload_object_check
      CHECK (jsonb_typeof(payload) = 'object');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'intel_event_stream_context_object_check'
      AND conrelid = 'public.intel_event_stream'::regclass
  ) THEN
    ALTER TABLE public.intel_event_stream
      ADD CONSTRAINT intel_event_stream_context_object_check
      CHECK (jsonb_typeof(context) = 'object');
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_intel_event_stream_event_id_unique
  ON public.intel_event_stream (event_id)
  WHERE event_id IS NOT NULL AND char_length(trim(event_id)) > 0;

CREATE INDEX IF NOT EXISTS idx_intel_event_stream_occurred_at_desc
  ON public.intel_event_stream (occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_intel_event_stream_ingested_at_desc
  ON public.intel_event_stream (ingested_at DESC);

CREATE INDEX IF NOT EXISTS idx_intel_event_stream_event_name_occurred_at
  ON public.intel_event_stream (event_name, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_intel_event_stream_session_id_occurred_at
  ON public.intel_event_stream (session_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_intel_event_stream_source_occurred_at
  ON public.intel_event_stream (source, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_intel_event_stream_payload_gin
  ON public.intel_event_stream USING gin (payload jsonb_path_ops);

CREATE INDEX IF NOT EXISTS idx_intel_event_stream_context_gin
  ON public.intel_event_stream USING gin (context jsonb_path_ops);

ALTER TABLE public.intel_event_stream ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intel_event_stream FORCE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'intel_event_stream'
      AND policyname = 'intel_event_stream_service_role_select'
  ) THEN
    CREATE POLICY intel_event_stream_service_role_select
      ON public.intel_event_stream
      FOR SELECT
      TO service_role
      USING (true);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'intel_event_stream'
      AND policyname = 'intel_event_stream_service_role_insert'
  ) THEN
    CREATE POLICY intel_event_stream_service_role_insert
      ON public.intel_event_stream
      FOR INSERT
      TO service_role
      WITH CHECK (true);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'intel_event_stream'
      AND policyname = 'intel_event_stream_service_role_delete'
  ) THEN
    CREATE POLICY intel_event_stream_service_role_delete
      ON public.intel_event_stream
      FOR DELETE
      TO service_role
      USING (true);
  END IF;
END
$$;

REVOKE ALL ON TABLE public.intel_event_stream FROM anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.intel_event_stream TO service_role;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relkind = 'S'
      AND relname = 'intel_event_stream_id_seq'
      AND relnamespace = 'public'::regnamespace
  ) THEN
    GRANT USAGE, SELECT ON SEQUENCE public.intel_event_stream_id_seq TO service_role;
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION public.purge_intel_event_stream(retain_days integer DEFAULT 30)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  keep_days integer := GREATEST(1, COALESCE(retain_days, 30));
  deleted_count integer := 0;
BEGIN
  DELETE FROM public.intel_event_stream
  WHERE occurred_at < (now() - make_interval(days => keep_days));

  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

REVOKE ALL ON FUNCTION public.purge_intel_event_stream(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.purge_intel_event_stream(integer) TO service_role;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron')
    AND EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'cron') THEN
    BEGIN
      PERFORM cron.unschedule(jobid)
      FROM cron.job
      WHERE jobname = 'purge_intel_event_stream_daily';
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;

    BEGIN
      PERFORM cron.schedule(
        'purge_intel_event_stream_daily',
        '15 3 * * *',
        'SELECT public.purge_intel_event_stream(30);'
      );
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END IF;
END
$$;

COMMENT ON TABLE public.intel_event_stream IS
'Signed canonical telemetry stream for ALIDADE runtime intel ingest.';

COMMENT ON FUNCTION public.purge_intel_event_stream(integer) IS
'Deletes stale intel_event_stream rows older than retain_days (default: 30).';

COMMIT;
