BEGIN;

ALTER TABLE public.intel_event_stream
  DROP CONSTRAINT IF EXISTS intel_event_stream_event_name_check;

ALTER TABLE public.intel_event_stream
  ADD CONSTRAINT intel_event_stream_event_name_check
  CHECK (event_name = ANY (ARRAY[
    'price.quote_seen',
    'price.anomaly_detected',
    'price.crowd_submitted',
    'negotiation.round_recorded',
    'hazard.zone_state_changed',
    'sos.armed',
    'sos.triggered',
    'sos.deactivated',
    'context.update',
    'threat.report_submitted',
    'threat.report_deduped',
    'threat.report_rate_limited',
    'threat.node_status_changed',
    'nav.state_changed',
    'nav.guidance_issued',
    'nav.guidance_marked_false',
    'nav.recovery_started',
    'nav.recovery_action_presented',
    'nav.recovery_completed'
  ]));

CREATE TABLE IF NOT EXISTS public.threat_device_stats (
  device_hash text PRIMARY KEY,
  accepted_count integer NOT NULL DEFAULT 0 CHECK (accepted_count >= 0),
  rejected_count integer NOT NULL DEFAULT 0 CHECK (rejected_count >= 0),
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.threat_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id text,
  occurred_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  session_id text NOT NULL,
  source text NOT NULL DEFAULT 'unknown',
  source_module text NOT NULL DEFAULT 'unknown',
  device_hash text NOT NULL,
  geohash7 text NOT NULL,
  category text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
  severity_score integer NOT NULL CHECK (severity_score >= 1 AND severity_score <= 3),
  weight numeric(8,3) NOT NULL DEFAULT 1.000 CHECK (weight >= 0),
  dedupe_key text NOT NULL,
  is_contradictory boolean NOT NULL DEFAULT false,
  zone_id text,
  CHECK (geohash7 ~* '^[0123456789bcdefghjkmnpqrstuvwxyz]{7}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_threat_reports_dedupe_key_unique
  ON public.threat_reports (dedupe_key);

CREATE INDEX IF NOT EXISTS idx_threat_reports_device_ingested
  ON public.threat_reports (device_hash, ingested_at DESC);

CREATE INDEX IF NOT EXISTS idx_threat_reports_geo_category_occurred
  ON public.threat_reports (geohash7, category, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_threat_reports_event_id
  ON public.threat_reports (event_id)
  WHERE event_id IS NOT NULL AND char_length(trim(event_id)) > 0;

CREATE TABLE IF NOT EXISTS public.threat_nodes (
  geohash7 text NOT NULL,
  category text NOT NULL,
  status text NOT NULL DEFAULT 'unverified' CHECK (status IN ('unverified', 'provisional', 'verified')),
  weighted_score numeric(10,3) NOT NULL DEFAULT 0.000 CHECK (weighted_score >= 0),
  agreement_score numeric(6,3) NOT NULL DEFAULT 0.000 CHECK (agreement_score >= 0 AND agreement_score <= 1),
  report_count_4h integer NOT NULL DEFAULT 0 CHECK (report_count_4h >= 0),
  report_count_24h integer NOT NULL DEFAULT 0 CHECK (report_count_24h >= 0),
  unique_devices_4h integer NOT NULL DEFAULT 0 CHECK (unique_devices_4h >= 0),
  unique_devices_24h integer NOT NULL DEFAULT 0 CHECK (unique_devices_24h >= 0),
  contradiction_count_24h integer NOT NULL DEFAULT 0 CHECK (contradiction_count_24h >= 0),
  last_signal_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (geohash7, category),
  CHECK (geohash7 ~* '^[0123456789bcdefghjkmnpqrstuvwxyz]{7}$')
);

CREATE INDEX IF NOT EXISTS idx_threat_nodes_status_updated
  ON public.threat_nodes (status, updated_at DESC);

ALTER TABLE public.threat_device_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.threat_device_stats FORCE ROW LEVEL SECURITY;
ALTER TABLE public.threat_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.threat_reports FORCE ROW LEVEL SECURITY;
ALTER TABLE public.threat_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.threat_nodes FORCE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'threat_device_stats' AND policyname = 'threat_device_stats_service_role_all'
  ) THEN
    CREATE POLICY threat_device_stats_service_role_all
      ON public.threat_device_stats
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'threat_reports' AND policyname = 'threat_reports_service_role_all'
  ) THEN
    CREATE POLICY threat_reports_service_role_all
      ON public.threat_reports
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'threat_nodes' AND policyname = 'threat_nodes_service_role_all'
  ) THEN
    CREATE POLICY threat_nodes_service_role_all
      ON public.threat_nodes
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END
$$;

REVOKE ALL ON TABLE public.threat_device_stats FROM anon, authenticated;
REVOKE ALL ON TABLE public.threat_reports FROM anon, authenticated;
REVOKE ALL ON TABLE public.threat_nodes FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.threat_device_stats TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.threat_reports TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.threat_nodes TO service_role;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relkind = 'S'
      AND relname = 'threat_reports_id_seq'
      AND relnamespace = 'public'::regnamespace
  ) THEN
    GRANT USAGE, SELECT ON SEQUENCE public.threat_reports_id_seq TO service_role;
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION public.intel_nav_quality_metrics(window_hours integer DEFAULT 24)
RETURNS TABLE (
  window_hours integer,
  guidance_issued bigint,
  guidance_marked_false bigint,
  false_guidance_rate numeric,
  recovery_started bigint,
  recovery_completed bigint,
  p95_recovery_ms numeric,
  p95_time_to_first_action_ms numeric
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
WITH windowed AS (
  SELECT event_name, occurred_at, session_id, payload
  FROM public.intel_event_stream
  WHERE occurred_at >= now() - make_interval(hours => GREATEST(1, COALESCE(window_hours, 24)))
),
counts AS (
  SELECT
    COUNT(*) FILTER (WHERE event_name = 'nav.guidance_issued')::bigint AS guidance_issued,
    COUNT(*) FILTER (WHERE event_name = 'nav.guidance_marked_false')::bigint AS guidance_marked_false,
    COUNT(*) FILTER (WHERE event_name = 'nav.recovery_started')::bigint AS recovery_started,
    COUNT(*) FILTER (WHERE event_name = 'nav.recovery_completed')::bigint AS recovery_completed
  FROM windowed
),
recovery_metrics AS (
  SELECT
    percentile_cont(0.95) WITHIN GROUP (
      ORDER BY NULLIF((payload ->> 'elapsed_ms')::numeric, NULL)
    ) AS p95_recovery_ms
  FROM windowed
  WHERE event_name = 'nav.recovery_completed'
    AND (payload ->> 'elapsed_ms') ~ '^[0-9]+(\.[0-9]+)?$'
),
action_pairs AS (
  SELECT
    s.session_id,
    EXTRACT(EPOCH FROM (a.occurred_at - s.occurred_at)) * 1000 AS action_ms
  FROM windowed s
  JOIN LATERAL (
    SELECT occurred_at
    FROM windowed a
    WHERE a.event_name = 'nav.recovery_action_presented'
      AND a.session_id = s.session_id
      AND a.occurred_at >= s.occurred_at
    ORDER BY a.occurred_at ASC
    LIMIT 1
  ) a ON true
  WHERE s.event_name = 'nav.state_changed'
    AND COALESCE(s.payload ->> 'to_state', '') IN ('LOST', 'PANIC')
),
action_metrics AS (
  SELECT percentile_cont(0.95) WITHIN GROUP (ORDER BY action_ms) AS p95_time_to_first_action_ms
  FROM action_pairs
  WHERE action_ms >= 0
)
SELECT
  GREATEST(1, COALESCE($1, 24))::integer,
  counts.guidance_issued,
  counts.guidance_marked_false,
  CASE
    WHEN counts.guidance_issued = 0 THEN 0::numeric
    ELSE ROUND((counts.guidance_marked_false::numeric / counts.guidance_issued::numeric), 6)
  END AS false_guidance_rate,
  counts.recovery_started,
  counts.recovery_completed,
  COALESCE(recovery_metrics.p95_recovery_ms, 0)::numeric,
  COALESCE(action_metrics.p95_time_to_first_action_ms, 0)::numeric
FROM counts
CROSS JOIN recovery_metrics
CROSS JOIN action_metrics;
$$;

REVOKE ALL ON FUNCTION public.intel_nav_quality_metrics(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.intel_nav_quality_metrics(integer) TO service_role;

COMMIT;
